import type { EndpointDef } from "../types.js";

export const accountEndpoints: EndpointDef[] = [
  {
    domain: "accounts",
    action: "list",
    method: "GET",
    path: "/admin/accounts",
    queryParams: [
      { name: "page", type: "number", required: false, description: "页码" },
      { name: "page_size", type: "number", required: false, description: "每页数量" },
      { name: "sort_by", type: "string", required: false, description: "排序字段" },
      { name: "sort_order", type: "string", required: false, description: "asc/desc" },
      { name: "status", type: "string", required: false, description: "状态筛选" },
      { name: "platform", type: "string", required: false, description: "平台筛选" },
      { name: "search", type: "string", required: false, description: "搜索关键词" },
    ],
    isPaginated: true,
    description: "列出所有账号",
    aliases: ["ls"],
  },
  {
    domain: "accounts",
    action: "get",
    method: "GET",
    path: "/admin/accounts/:id",
    pathParams: [{ name: "id", type: "number", required: true, description: "账号 ID" }],
    description: "获取账号详情",
  },
  {
    domain: "accounts",
    action: "create",
    method: "POST",
    path: "/admin/accounts",
    rawBody: true,
    description: "创建账号 (使用 --json 传入完整配置)",
  },
  {
    domain: "accounts",
    action: "update",
    method: "PUT",
    path: "/admin/accounts/:id",
    pathParams: [{ name: "id", type: "number", required: true, description: "账号 ID" }],
    rawBody: true,
    description: "更新账号 (使用 --json 传入更新字段)",
  },
  {
    domain: "accounts",
    action: "delete",
    method: "DELETE",
    path: "/admin/accounts/:id",
    pathParams: [{ name: "id", type: "number", required: true, description: "账号 ID" }],
    description: "删除账号",
  },
  {
    domain: "accounts",
    action: "test",
    method: "POST",
    path: "/admin/accounts/:id/test",
    pathParams: [{ name: "id", type: "number", required: true, description: "账号 ID" }],
    description: "测试账号连通性",
  },
  {
    domain: "accounts",
    action: "recover-state",
    method: "POST",
    path: "/admin/accounts/:id/recover-state",
    pathParams: [{ name: "id", type: "number", required: true, description: "账号 ID" }],
    description: "恢复账号状态",
  },
  {
    domain: "accounts",
    action: "refresh",
    method: "POST",
    path: "/admin/accounts/:id/refresh",
    pathParams: [{ name: "id", type: "number", required: true, description: "账号 ID" }],
    description: "刷新账号",
  },
  {
    domain: "accounts",
    action: "apply-oauth",
    method: "POST",
    path: "/admin/accounts/:id/apply-oauth-credentials",
    pathParams: [{ name: "id", type: "number", required: true, description: "账号 ID" }],
    description: "应用 OAuth 凭据",
  },
  {
    domain: "accounts",
    action: "set-privacy",
    method: "POST",
    path: "/admin/accounts/:id/set-privacy",
    pathParams: [{ name: "id", type: "number", required: true, description: "账号 ID" }],
    rawBody: true,
    description: "设置隐私模式",
  },
  {
    domain: "accounts",
    action: "refresh-tier",
    method: "POST",
    path: "/admin/accounts/:id/refresh-tier",
    pathParams: [{ name: "id", type: "number", required: true, description: "账号 ID" }],
    description: "刷新账号等级",
  },
  {
    domain: "accounts",
    action: "stats",
    method: "GET",
    path: "/admin/accounts/:id/stats",
    pathParams: [{ name: "id", type: "number", required: true, description: "账号 ID" }],
    description: "获取账号统计",
  },
  {
    domain: "accounts",
    action: "clear-error",
    method: "POST",
    path: "/admin/accounts/:id/clear-error",
    pathParams: [{ name: "id", type: "number", required: true, description: "账号 ID" }],
    description: "清除账号错误",
  },
  {
    domain: "accounts",
    action: "revert-proxy-fallback",
    method: "POST",
    path: "/admin/accounts/:id/revert-proxy-fallback",
    pathParams: [{ name: "id", type: "number", required: true, description: "账号 ID" }],
    description: "回退代理降级",
  },
  {
    domain: "accounts",
    action: "usage",
    method: "GET",
    path: "/admin/accounts/:id/usage",
    pathParams: [{ name: "id", type: "number", required: true, description: "账号 ID" }],
    description: "获取账号用量",
  },
  {
    domain: "accounts",
    action: "today-stats",
    method: "GET",
    path: "/admin/accounts/:id/today-stats",
    pathParams: [{ name: "id", type: "number", required: true, description: "账号 ID" }],
    description: "获取账号今日统计",
  },
  {
    domain: "accounts",
    action: "batch-today-stats",
    method: "POST",
    path: "/admin/accounts/today-stats/batch",
    rawBody: true,
    description: "批量获取账号今日统计",
  },
  {
    domain: "accounts",
    action: "clear-rate-limit",
    method: "POST",
    path: "/admin/accounts/:id/clear-rate-limit",
    pathParams: [{ name: "id", type: "number", required: true, description: "账号 ID" }],
    description: "清除账号速率限制",
  },
  {
    domain: "accounts",
    action: "reset-quota",
    method: "POST",
    path: "/admin/accounts/:id/reset-quota",
    pathParams: [{ name: "id", type: "number", required: true, description: "账号 ID" }],
    description: "重置账号配额",
  },
  {
    domain: "accounts",
    action: "temp-unschedulable",
    method: "GET",
    path: "/admin/accounts/:id/temp-unschedulable",
    pathParams: [{ name: "id", type: "number", required: true, description: "账号 ID" }],
    description: "获取临时不可调度状态",
  },
  {
    domain: "accounts",
    action: "clear-temp-unschedulable",
    method: "DELETE",
    path: "/admin/accounts/:id/temp-unschedulable",
    pathParams: [{ name: "id", type: "number", required: true, description: "账号 ID" }],
    description: "清除临时不可调度",
  },
  {
    domain: "accounts",
    action: "set-schedulable",
    method: "POST",
    path: "/admin/accounts/:id/schedulable",
    pathParams: [{ name: "id", type: "number", required: true, description: "账号 ID" }],
    rawBody: true,
    description: "设置可调度状态",
  },
  {
    domain: "accounts",
    action: "models",
    method: "GET",
    path: "/admin/accounts/:id/models",
    pathParams: [{ name: "id", type: "number", required: true, description: "账号 ID" }],
    description: "获取可用模型列表",
  },
  {
    domain: "accounts",
    action: "sync-upstream-models",
    method: "POST",
    path: "/admin/accounts/:id/models/sync-upstream",
    pathParams: [{ name: "id", type: "number", required: true, description: "账号 ID" }],
    description: "同步上游模型",
  },
  {
    domain: "accounts",
    action: "sync-upstream-preview",
    method: "POST",
    path: "/admin/accounts/models/sync-upstream-preview",
    rawBody: true,
    description: "同步上游模型预览",
  },
  {
    domain: "accounts",
    action: "batch",
    method: "POST",
    path: "/admin/accounts/batch",
    rawBody: true,
    description: "批量创建账号",
  },
  {
    domain: "accounts",
    action: "check-mixed-channel",
    method: "POST",
    path: "/admin/accounts/check-mixed-channel",
    bodyParams: [
      { name: "platform", type: "string", required: true, description: "平台" },
      { name: "group_ids", type: "json", required: false, description: "分组 IDs (JSON 数组)" },
      { name: "account_id", type: "number", required: false, description: "账号 ID" },
    ],
    description: "检查混合渠道",
  },
  {
    domain: "accounts",
    action: "import-codex-session",
    method: "POST",
    path: "/admin/accounts/import/codex-session",
    rawBody: true,
    description: "导入 Codex Session",
  },
  {
    domain: "accounts",
    action: "sync-crs",
    method: "POST",
    path: "/admin/accounts/sync/crs",
    rawBody: true,
    description: "从 CRS 同步",
  },
  {
    domain: "accounts",
    action: "sync-crs-preview",
    method: "POST",
    path: "/admin/accounts/sync/crs/preview",
    rawBody: true,
    description: "从 CRS 同步预览",
  },
  {
    domain: "accounts",
    action: "export",
    method: "GET",
    path: "/admin/accounts/data",
    description: "导出账号数据",
  },
  {
    domain: "accounts",
    action: "import",
    method: "POST",
    path: "/admin/accounts/data",
    rawBody: true,
    description: "导入账号数据",
  },
  {
    domain: "accounts",
    action: "batch-update-credentials",
    method: "POST",
    path: "/admin/accounts/batch-update-credentials",
    rawBody: true,
    description: "批量更新凭据",
  },
  {
    domain: "accounts",
    action: "batch-refresh-tier",
    method: "POST",
    path: "/admin/accounts/batch-refresh-tier",
    rawBody: true,
    description: "批量刷新等级",
  },
  {
    domain: "accounts",
    action: "bulk-update",
    method: "POST",
    path: "/admin/accounts/bulk-update",
    rawBody: true,
    description: "批量更新账号",
  },
  {
    domain: "accounts",
    action: "batch-clear-error",
    method: "POST",
    path: "/admin/accounts/batch-clear-error",
    rawBody: true,
    description: "批量清除错误",
  },
  {
    domain: "accounts",
    action: "batch-refresh",
    method: "POST",
    path: "/admin/accounts/batch-refresh",
    rawBody: true,
    description: "批量刷新账号",
  },
  {
    domain: "accounts",
    action: "antigravity-model-mapping",
    method: "GET",
    path: "/admin/accounts/antigravity/default-model-mapping",
    description: "获取 Antigravity 默认模型映射",
  },
  // Claude OAuth 子路由
  {
    domain: "accounts",
    action: "generate-auth-url",
    method: "POST",
    path: "/admin/accounts/generate-auth-url",
    rawBody: true,
    description: "生成 Claude OAuth 认证 URL",
  },
  {
    domain: "accounts",
    action: "generate-setup-token-url",
    method: "POST",
    path: "/admin/accounts/generate-setup-token-url",
    rawBody: true,
    description: "生成 Setup Token URL",
  },
  {
    domain: "accounts",
    action: "exchange-code",
    method: "POST",
    path: "/admin/accounts/exchange-code",
    rawBody: true,
    description: "交换 OAuth Code",
  },
  {
    domain: "accounts",
    action: "exchange-setup-token-code",
    method: "POST",
    path: "/admin/accounts/exchange-setup-token-code",
    rawBody: true,
    description: "交换 Setup Token Code",
  },
  {
    domain: "accounts",
    action: "cookie-auth",
    method: "POST",
    path: "/admin/accounts/cookie-auth",
    rawBody: true,
    description: "Cookie 认证",
  },
  {
    domain: "accounts",
    action: "setup-token-cookie-auth",
    method: "POST",
    path: "/admin/accounts/setup-token-cookie-auth",
    rawBody: true,
    description: "Setup Token Cookie 认证",
  },
];
