import type { EndpointDef } from "../types.js";

export const announcementEndpoints: EndpointDef[] = [
  {
    domain: "announcements",
    action: "list",
    method: "GET",
    path: "/admin/announcements",
    queryParams: [
      { name: "page", type: "number", required: false, description: "页码" },
      { name: "page_size", type: "number", required: false, description: "每页数量" },
      { name: "status", type: "string", required: false, description: "状态筛选" },
      { name: "search", type: "string", required: false, description: "搜索关键词" },
      { name: "sort_by", type: "string", required: false, description: "排序字段" },
      { name: "sort_order", type: "string", required: false, description: "asc/desc" },
    ],
    isPaginated: true,
    description: "列出所有公告",
    aliases: ["ls"],
  },
  {
    domain: "announcements",
    action: "create",
    method: "POST",
    path: "/admin/announcements",
    bodyParams: [
      { name: "title", type: "string", required: true, description: "标题" },
      { name: "content", type: "string", required: true, description: "内容" },
      { name: "status", type: "string", required: false, description: "状态" },
      { name: "notify_mode", type: "string", required: false, description: "通知模式" },
      { name: "targeting", type: "json", required: false, description: "目标对象 (JSON)" },
      { name: "starts_at", type: "string", required: false, description: "开始时间" },
      { name: "ends_at", type: "string", required: false, description: "结束时间" },
    ],
    description: "创建公告",
  },
  {
    domain: "announcements",
    action: "get",
    method: "GET",
    path: "/admin/announcements/:id",
    pathParams: [{ name: "id", type: "number", required: true, description: "公告 ID" }],
    description: "获取公告详情",
  },
  {
    domain: "announcements",
    action: "update",
    method: "PUT",
    path: "/admin/announcements/:id",
    pathParams: [{ name: "id", type: "number", required: true, description: "公告 ID" }],
    rawBody: true,
    description: "更新公告 (使用 --json 传入更新字段)",
  },
  {
    domain: "announcements",
    action: "delete",
    method: "DELETE",
    path: "/admin/announcements/:id",
    pathParams: [{ name: "id", type: "number", required: true, description: "公告 ID" }],
    description: "删除公告",
  },
  {
    domain: "announcements",
    action: "read-status",
    method: "GET",
    path: "/admin/announcements/:id/read-status",
    pathParams: [{ name: "id", type: "number", required: true, description: "公告 ID" }],
    description: "获取公告已读状态",
  },
];
