import type { EndpointDef } from "../types.js";

export const channelEndpoints: EndpointDef[] = [
  {
    domain: "channels",
    action: "list",
    method: "GET",
    path: "/admin/channels",
    queryParams: [
      { name: "page", type: "number", required: false, description: "页码" },
      { name: "page_size", type: "number", required: false, description: "每页数量" },
    ],
    isPaginated: true,
    description: "列出所有渠道",
    aliases: ["ls"],
  },
  {
    domain: "channels",
    action: "model-pricing",
    method: "GET",
    path: "/admin/channels/model-pricing",
    description: "获取模型默认定价",
  },
  {
    domain: "channels",
    action: "sync-models",
    method: "GET",
    path: "/admin/channels/pricing/sync-models",
    description: "同步定价模型列表",
  },
  {
    domain: "channels",
    action: "get",
    method: "GET",
    path: "/admin/channels/:id",
    pathParams: [{ name: "id", type: "number", required: true, description: "渠道 ID" }],
    description: "获取渠道详情",
  },
  {
    domain: "channels",
    action: "create",
    method: "POST",
    path: "/admin/channels",
    rawBody: true,
    description: "创建渠道 (使用 --json 传入)",
  },
  {
    domain: "channels",
    action: "update",
    method: "PUT",
    path: "/admin/channels/:id",
    pathParams: [{ name: "id", type: "number", required: true, description: "渠道 ID" }],
    rawBody: true,
    description: "更新渠道 (使用 --json 传入更新字段)",
  },
  {
    domain: "channels",
    action: "delete",
    method: "DELETE",
    path: "/admin/channels/:id",
    pathParams: [{ name: "id", type: "number", required: true, description: "渠道 ID" }],
    description: "删除渠道",
  },
];

export const channelMonitorEndpoints: EndpointDef[] = [
  {
    domain: "channel-monitors",
    action: "list",
    method: "GET",
    path: "/admin/channel-monitors",
    description: "列出渠道监控",
    aliases: ["ls"],
  },
  {
    domain: "channel-monitors",
    action: "create",
    method: "POST",
    path: "/admin/channel-monitors",
    rawBody: true,
    description: "创建渠道监控 (使用 --json 传入)",
  },
  {
    domain: "channel-monitors",
    action: "get",
    method: "GET",
    path: "/admin/channel-monitors/:id",
    pathParams: [{ name: "id", type: "number", required: true, description: "监控 ID" }],
    description: "获取渠道监控详情",
  },
  {
    domain: "channel-monitors",
    action: "update",
    method: "PUT",
    path: "/admin/channel-monitors/:id",
    pathParams: [{ name: "id", type: "number", required: true, description: "监控 ID" }],
    rawBody: true,
    description: "更新渠道监控 (使用 --json 传入)",
  },
  {
    domain: "channel-monitors",
    action: "delete",
    method: "DELETE",
    path: "/admin/channel-monitors/:id",
    pathParams: [{ name: "id", type: "number", required: true, description: "监控 ID" }],
    description: "删除渠道监控",
  },
  {
    domain: "channel-monitors",
    action: "run",
    method: "POST",
    path: "/admin/channel-monitors/:id/run",
    pathParams: [{ name: "id", type: "number", required: true, description: "监控 ID" }],
    description: "运行渠道监控",
  },
  {
    domain: "channel-monitors",
    action: "history",
    method: "GET",
    path: "/admin/channel-monitors/:id/history",
    pathParams: [{ name: "id", type: "number", required: true, description: "监控 ID" }],
    description: "获取监控历史",
  },
];

export const channelMonitorTemplateEndpoints: EndpointDef[] = [
  {
    domain: "channel-monitor-templates",
    action: "list",
    method: "GET",
    path: "/admin/channel-monitor-templates",
    description: "列出监控模板",
    aliases: ["ls"],
  },
  {
    domain: "channel-monitor-templates",
    action: "create",
    method: "POST",
    path: "/admin/channel-monitor-templates",
    rawBody: true,
    description: "创建监控模板 (使用 --json 传入)",
  },
  {
    domain: "channel-monitor-templates",
    action: "get",
    method: "GET",
    path: "/admin/channel-monitor-templates/:id",
    pathParams: [{ name: "id", type: "number", required: true, description: "模板 ID" }],
    description: "获取监控模板详情",
  },
  {
    domain: "channel-monitor-templates",
    action: "update",
    method: "PUT",
    path: "/admin/channel-monitor-templates/:id",
    pathParams: [{ name: "id", type: "number", required: true, description: "模板 ID" }],
    rawBody: true,
    description: "更新监控模板 (使用 --json 传入)",
  },
  {
    domain: "channel-monitor-templates",
    action: "delete",
    method: "DELETE",
    path: "/admin/channel-monitor-templates/:id",
    pathParams: [{ name: "id", type: "number", required: true, description: "模板 ID" }],
    description: "删除监控模板",
  },
  {
    domain: "channel-monitor-templates",
    action: "monitors",
    method: "GET",
    path: "/admin/channel-monitor-templates/:id/monitors",
    pathParams: [{ name: "id", type: "number", required: true, description: "模板 ID" }],
    description: "获取模板关联的监控",
  },
  {
    domain: "channel-monitor-templates",
    action: "apply",
    method: "POST",
    path: "/admin/channel-monitor-templates/:id/apply",
    pathParams: [{ name: "id", type: "number", required: true, description: "模板 ID" }],
    rawBody: true,
    description: "应用监控模板",
  },
];
