import type { EndpointDef } from "../types.js";

export const dashboardEndpoints: EndpointDef[] = [
  {
    domain: "dashboard",
    action: "snapshot",
    method: "GET",
    path: "/admin/dashboard/snapshot-v2",
    description: "获取仪表盘快照 V2",
  },
  {
    domain: "dashboard",
    action: "stats",
    method: "GET",
    path: "/admin/dashboard/stats",
    description: "获取统计数据",
  },
  {
    domain: "dashboard",
    action: "realtime",
    method: "GET",
    path: "/admin/dashboard/realtime",
    description: "获取实时指标",
  },
  {
    domain: "dashboard",
    action: "trend",
    method: "GET",
    path: "/admin/dashboard/trend",
    description: "获取用量趋势",
  },
  {
    domain: "dashboard",
    action: "models",
    method: "GET",
    path: "/admin/dashboard/models",
    description: "获取模型统计",
  },
  {
    domain: "dashboard",
    action: "groups",
    method: "GET",
    path: "/admin/dashboard/groups",
    description: "获取分组统计",
  },
  {
    domain: "dashboard",
    action: "api-keys-trend",
    method: "GET",
    path: "/admin/dashboard/api-keys-trend",
    description: "获取 API Key 用量趋势",
  },
  {
    domain: "dashboard",
    action: "users-trend",
    method: "GET",
    path: "/admin/dashboard/users-trend",
    description: "获取用户用量趋势",
  },
  {
    domain: "dashboard",
    action: "users-ranking",
    method: "GET",
    path: "/admin/dashboard/users-ranking",
    description: "获取用户消费排行",
  },
  {
    domain: "dashboard",
    action: "users-usage",
    method: "POST",
    path: "/admin/dashboard/users-usage",
    rawBody: true,
    description: "批量获取用户用量",
  },
  {
    domain: "dashboard",
    action: "api-keys-usage",
    method: "POST",
    path: "/admin/dashboard/api-keys-usage",
    rawBody: true,
    description: "批量获取 API Key 用量",
  },
  {
    domain: "dashboard",
    action: "user-breakdown",
    method: "GET",
    path: "/admin/dashboard/user-breakdown",
    description: "获取用户用量分解",
  },
  {
    domain: "dashboard",
    action: "backfill",
    method: "POST",
    path: "/admin/dashboard/aggregation/backfill",
    rawBody: true,
    description: "回填聚合数据",
  },
];
