import type { EndpointDef } from "../types.js";

export const groupEndpoints: EndpointDef[] = [
  {
    domain: "groups",
    action: "list",
    method: "GET",
    path: "/admin/groups",
    queryParams: [
      { name: "page", type: "number", required: false, description: "页码" },
      { name: "page_size", type: "number", required: false, description: "每页数量" },
      { name: "sort_by", type: "string", required: false, description: "排序字段" },
      { name: "sort_order", type: "string", required: false, description: "asc/desc" },
    ],
    isPaginated: true,
    description: "列出所有分组",
    aliases: ["ls"],
  },
  {
    domain: "groups",
    action: "all",
    method: "GET",
    path: "/admin/groups/all",
    description: "获取全部分组（不分页）",
  },
  {
    domain: "groups",
    action: "usage-summary",
    method: "GET",
    path: "/admin/groups/usage-summary",
    description: "获取分组用量汇总",
  },
  {
    domain: "groups",
    action: "capacity-summary",
    method: "GET",
    path: "/admin/groups/capacity-summary",
    description: "获取分组容量汇总",
  },
  {
    domain: "groups",
    action: "update-sort-order",
    method: "PUT",
    path: "/admin/groups/sort-order",
    rawBody: true,
    description: "更新分组排序",
  },
  {
    domain: "groups",
    action: "get",
    method: "GET",
    path: "/admin/groups/:id",
    pathParams: [{ name: "id", type: "number", required: true, description: "分组 ID" }],
    description: "获取分组详情",
  },
  {
    domain: "groups",
    action: "create",
    method: "POST",
    path: "/admin/groups",
    rawBody: true,
    description: "创建分组 (使用 --json 传入完整配置)",
  },
  {
    domain: "groups",
    action: "update",
    method: "PUT",
    path: "/admin/groups/:id",
    pathParams: [{ name: "id", type: "number", required: true, description: "分组 ID" }],
    rawBody: true,
    description: "更新分组 (使用 --json 传入更新字段)",
  },
  {
    domain: "groups",
    action: "delete",
    method: "DELETE",
    path: "/admin/groups/:id",
    pathParams: [{ name: "id", type: "number", required: true, description: "分组 ID" }],
    description: "删除分组",
  },
  {
    domain: "groups",
    action: "stats",
    method: "GET",
    path: "/admin/groups/:id/stats",
    pathParams: [{ name: "id", type: "number", required: true, description: "分组 ID" }],
    description: "获取分组统计",
  },
  {
    domain: "groups",
    action: "rate-multipliers",
    method: "GET",
    path: "/admin/groups/:id/rate-multipliers",
    pathParams: [{ name: "id", type: "number", required: true, description: "分组 ID" }],
    description: "获取分组费率倍率",
  },
  {
    domain: "groups",
    action: "set-rate-multipliers",
    method: "PUT",
    path: "/admin/groups/:id/rate-multipliers",
    pathParams: [{ name: "id", type: "number", required: true, description: "分组 ID" }],
    rawBody: true,
    description: "批量设置分组费率倍率",
  },
  {
    domain: "groups",
    action: "clear-rate-multipliers",
    method: "DELETE",
    path: "/admin/groups/:id/rate-multipliers",
    pathParams: [{ name: "id", type: "number", required: true, description: "分组 ID" }],
    description: "清除分组费率倍率",
  },
  {
    domain: "groups",
    action: "set-rpm-overrides",
    method: "PUT",
    path: "/admin/groups/:id/rpm-overrides",
    pathParams: [{ name: "id", type: "number", required: true, description: "分组 ID" }],
    rawBody: true,
    description: "批量设置分组 RPM 覆盖",
  },
  {
    domain: "groups",
    action: "clear-rpm-overrides",
    method: "DELETE",
    path: "/admin/groups/:id/rpm-overrides",
    pathParams: [{ name: "id", type: "number", required: true, description: "分组 ID" }],
    description: "清除分组 RPM 覆盖",
  },
  {
    domain: "groups",
    action: "api-keys",
    method: "GET",
    path: "/admin/groups/:id/api-keys",
    pathParams: [{ name: "id", type: "number", required: true, description: "分组 ID" }],
    description: "获取分组 API Keys",
  },
  {
    domain: "groups",
    action: "models-list-candidates",
    method: "GET",
    path: "/admin/groups/:id/models-list-candidates",
    pathParams: [{ name: "id", type: "number", required: true, description: "分组 ID" }],
    description: "获取分组可选模型列表候选",
  },
  {
    domain: "groups",
    action: "subscriptions",
    method: "GET",
    path: "/admin/groups/:id/subscriptions",
    pathParams: [{ name: "id", type: "number", required: true, description: "分组 ID" }],
    queryParams: [
      { name: "page", type: "number", required: false, description: "页码" },
      { name: "page_size", type: "number", required: false, description: "每页数量" },
    ],
    isPaginated: true,
    description: "获取分组订阅列表",
  },
];
