import type { EndpointDef } from "../types.js";

export const proxyEndpoints: EndpointDef[] = [
  {
    domain: "proxies",
    action: "list",
    method: "GET",
    path: "/admin/proxies",
    queryParams: [
      { name: "page", type: "number", required: false, description: "页码" },
      { name: "page_size", type: "number", required: false, description: "每页数量" },
      { name: "protocol", type: "string", required: false, description: "协议筛选" },
      { name: "status", type: "string", required: false, description: "状态筛选" },
      { name: "search", type: "string", required: false, description: "搜索关键词" },
      { name: "sort_by", type: "string", required: false, description: "排序字段" },
      { name: "sort_order", type: "string", required: false, description: "asc/desc" },
    ],
    isPaginated: true,
    description: "列出所有代理",
    aliases: ["ls"],
  },
  {
    domain: "proxies",
    action: "all",
    method: "GET",
    path: "/admin/proxies/all",
    queryParams: [
      { name: "with_count", type: "boolean", required: false, description: "包含关联账号数" },
    ],
    description: "获取全部代理（不分页）",
  },
  {
    domain: "proxies",
    action: "export",
    method: "GET",
    path: "/admin/proxies/data",
    description: "导出代理数据",
  },
  {
    domain: "proxies",
    action: "import",
    method: "POST",
    path: "/admin/proxies/data",
    rawBody: true,
    description: "导入代理数据",
  },
  {
    domain: "proxies",
    action: "get",
    method: "GET",
    path: "/admin/proxies/:id",
    pathParams: [{ name: "id", type: "number", required: true, description: "代理 ID" }],
    description: "获取代理详情",
  },
  {
    domain: "proxies",
    action: "create",
    method: "POST",
    path: "/admin/proxies",
    bodyParams: [
      { name: "name", type: "string", required: true, description: "代理名称" },
      { name: "protocol", type: "string", required: true, description: "协议 (http/https/socks5)" },
      { name: "host", type: "string", required: true, description: "主机" },
      { name: "port", type: "number", required: true, description: "端口" },
      { name: "username", type: "string", required: false, description: "用户名" },
      { name: "password", type: "string", required: false, description: "密码" },
      { name: "expires_at", type: "string", required: false, description: "过期时间" },
      { name: "fallback_mode", type: "string", required: false, description: "降级模式" },
      { name: "backup_proxy_id", type: "number", required: false, description: "备用代理 ID" },
      { name: "expiry_warn_days", type: "number", required: false, description: "过期预警天数" },
    ],
    description: "创建代理",
  },
  {
    domain: "proxies",
    action: "update",
    method: "PUT",
    path: "/admin/proxies/:id",
    pathParams: [{ name: "id", type: "number", required: true, description: "代理 ID" }],
    rawBody: true,
    description: "更新代理 (使用 --json 传入更新字段)",
  },
  {
    domain: "proxies",
    action: "delete",
    method: "DELETE",
    path: "/admin/proxies/:id",
    pathParams: [{ name: "id", type: "number", required: true, description: "代理 ID" }],
    description: "删除代理",
  },
  {
    domain: "proxies",
    action: "test",
    method: "POST",
    path: "/admin/proxies/:id/test",
    pathParams: [{ name: "id", type: "number", required: true, description: "代理 ID" }],
    description: "测试代理连通性",
  },
  {
    domain: "proxies",
    action: "quality-check",
    method: "POST",
    path: "/admin/proxies/:id/quality-check",
    pathParams: [{ name: "id", type: "number", required: true, description: "代理 ID" }],
    description: "代理质量检查",
  },
  {
    domain: "proxies",
    action: "stats",
    method: "GET",
    path: "/admin/proxies/:id/stats",
    pathParams: [{ name: "id", type: "number", required: true, description: "代理 ID" }],
    description: "获取代理统计",
  },
  {
    domain: "proxies",
    action: "accounts",
    method: "GET",
    path: "/admin/proxies/:id/accounts",
    pathParams: [{ name: "id", type: "number", required: true, description: "代理 ID" }],
    description: "获取代理关联的账号",
  },
  {
    domain: "proxies",
    action: "batch-delete",
    method: "POST",
    path: "/admin/proxies/batch-delete",
    rawBody: true,
    description: "批量删除代理",
  },
  {
    domain: "proxies",
    action: "batch",
    method: "POST",
    path: "/admin/proxies/batch",
    rawBody: true,
    description: "批量创建代理",
  },
];
