import type { EndpointDef } from "../types.js";

export const redeemCodeEndpoints: EndpointDef[] = [
  {
    domain: "redeem-codes",
    action: "list",
    method: "GET",
    path: "/admin/redeem-codes",
    queryParams: [
      { name: "page", type: "number", required: false, description: "页码" },
      { name: "page_size", type: "number", required: false, description: "每页数量" },
      { name: "type", type: "string", required: false, description: "类型筛选" },
      { name: "status", type: "string", required: false, description: "状态筛选" },
      { name: "search", type: "string", required: false, description: "搜索关键词" },
      { name: "sort_by", type: "string", required: false, description: "排序字段" },
      { name: "sort_order", type: "string", required: false, description: "asc/desc" },
    ],
    isPaginated: true,
    description: "列出所有兑换码",
    aliases: ["ls"],
  },
  {
    domain: "redeem-codes",
    action: "stats",
    method: "GET",
    path: "/admin/redeem-codes/stats",
    description: "获取兑换码统计",
  },
  {
    domain: "redeem-codes",
    action: "export",
    method: "GET",
    path: "/admin/redeem-codes/export",
    description: "导出兑换码",
  },
  {
    domain: "redeem-codes",
    action: "get",
    method: "GET",
    path: "/admin/redeem-codes/:id",
    pathParams: [{ name: "id", type: "number", required: true, description: "兑换码 ID" }],
    description: "获取兑换码详情",
  },
  {
    domain: "redeem-codes",
    action: "create-and-redeem",
    method: "POST",
    path: "/admin/redeem-codes/create-and-redeem",
    bodyParams: [
      { name: "code", type: "string", required: true, description: "兑换码" },
      { name: "type", type: "string", required: false, description: "类型" },
      { name: "value", type: "number", required: true, description: "价值" },
      { name: "user_id", type: "number", required: true, description: "用户 ID" },
      { name: "group_id", type: "number", required: false, description: "分组 ID" },
      { name: "validity_days", type: "number", required: false, description: "有效天数" },
      { name: "notes", type: "string", required: false, description: "备注" },
      { name: "expires_at", type: "string", required: false, description: "过期时间" },
      { name: "expires_in_days", type: "number", required: false, description: "过期天数" },
    ],
    description: "创建并兑换",
  },
  {
    domain: "redeem-codes",
    action: "generate",
    method: "POST",
    path: "/admin/redeem-codes/generate",
    bodyParams: [
      { name: "count", type: "number", required: true, description: "数量" },
      { name: "type", type: "string", required: true, description: "类型" },
      { name: "value", type: "number", required: true, description: "价值" },
      { name: "group_id", type: "number", required: false, description: "分组 ID" },
      { name: "validity_days", type: "number", required: false, description: "有效天数" },
      { name: "expires_at", type: "string", required: false, description: "过期时间" },
      { name: "expires_in_days", type: "number", required: false, description: "过期天数" },
    ],
    description: "批量生成兑换码",
  },
  {
    domain: "redeem-codes",
    action: "delete",
    method: "DELETE",
    path: "/admin/redeem-codes/:id",
    pathParams: [{ name: "id", type: "number", required: true, description: "兑换码 ID" }],
    description: "删除兑换码",
  },
  {
    domain: "redeem-codes",
    action: "batch-delete",
    method: "POST",
    path: "/admin/redeem-codes/batch-delete",
    rawBody: true,
    description: "批量删除兑换码",
  },
  {
    domain: "redeem-codes",
    action: "batch-update",
    method: "POST",
    path: "/admin/redeem-codes/batch-update",
    rawBody: true,
    description: "批量更新兑换码",
  },
  {
    domain: "redeem-codes",
    action: "expire",
    method: "POST",
    path: "/admin/redeem-codes/:id/expire",
    pathParams: [{ name: "id", type: "number", required: true, description: "兑换码 ID" }],
    description: "使兑换码过期",
  },
];
