import type { EndpointDef } from "../types.js";

export const riskControlEndpoints: EndpointDef[] = [
  {
    domain: "risk-control",
    action: "config",
    method: "GET",
    path: "/admin/risk-control/config",
    description: "获取风控配置",
  },
  {
    domain: "risk-control",
    action: "update-config",
    method: "PUT",
    path: "/admin/risk-control/config",
    rawBody: true,
    description: "更新风控配置 (使用 --json 传入)",
  },
  {
    domain: "risk-control",
    action: "test-api-keys",
    method: "POST",
    path: "/admin/risk-control/api-keys/test",
    rawBody: true,
    description: "测试风控 API Keys",
  },
  {
    domain: "risk-control",
    action: "status",
    method: "GET",
    path: "/admin/risk-control/status",
    description: "获取风控状态",
  },
  {
    domain: "risk-control",
    action: "logs",
    method: "GET",
    path: "/admin/risk-control/logs",
    queryParams: [
      { name: "page", type: "number", required: false, description: "页码" },
      { name: "page_size", type: "number", required: false, description: "每页数量" },
    ],
    isPaginated: true,
    description: "列出风控日志",
  },
  {
    domain: "risk-control",
    action: "unban-user",
    method: "POST",
    path: "/admin/risk-control/users/:user_id/unban",
    pathParams: [{ name: "user_id", type: "number", required: true, description: "用户 ID" }],
    description: "解封用户",
  },
  {
    domain: "risk-control",
    action: "delete-hash",
    method: "DELETE",
    path: "/admin/risk-control/hashes",
    rawBody: true,
    description: "删除标记的 Hash",
  },
  {
    domain: "risk-control",
    action: "clear-hashes",
    method: "DELETE",
    path: "/admin/risk-control/hashes/all",
    description: "清除所有标记的 Hash",
  },
];

export const affiliateEndpoints: EndpointDef[] = [
  {
    domain: "affiliates",
    action: "invites",
    method: "GET",
    path: "/admin/affiliates/invites",
    queryParams: [
      { name: "page", type: "number", required: false, description: "页码" },
      { name: "page_size", type: "number", required: false, description: "每页数量" },
    ],
    isPaginated: true,
    description: "列出邀请记录",
  },
  {
    domain: "affiliates",
    action: "rebates",
    method: "GET",
    path: "/admin/affiliates/rebates",
    queryParams: [
      { name: "page", type: "number", required: false, description: "页码" },
      { name: "page_size", type: "number", required: false, description: "每页数量" },
    ],
    isPaginated: true,
    description: "列出返利记录",
  },
  {
    domain: "affiliates",
    action: "transfers",
    method: "GET",
    path: "/admin/affiliates/transfers",
    queryParams: [
      { name: "page", type: "number", required: false, description: "页码" },
      { name: "page_size", type: "number", required: false, description: "每页数量" },
    ],
    isPaginated: true,
    description: "列出转账记录",
  },
  {
    domain: "affiliates",
    action: "users",
    method: "GET",
    path: "/admin/affiliates/users",
    description: "列出返利用户",
  },
  {
    domain: "affiliates",
    action: "lookup-users",
    method: "GET",
    path: "/admin/affiliates/users/lookup",
    queryParams: [
      { name: "search", type: "string", required: false, description: "搜索关键词" },
    ],
    description: "查找返利用户",
  },
  {
    domain: "affiliates",
    action: "batch-set-rate",
    method: "POST",
    path: "/admin/affiliates/users/batch-rate",
    rawBody: true,
    description: "批量设置返利比例",
  },
  {
    domain: "affiliates",
    action: "user-overview",
    method: "GET",
    path: "/admin/affiliates/users/:user_id/overview",
    pathParams: [{ name: "user_id", type: "number", required: true, description: "用户 ID" }],
    description: "获取用户返利概览",
  },
  {
    domain: "affiliates",
    action: "update-user",
    method: "PUT",
    path: "/admin/affiliates/users/:user_id",
    pathParams: [{ name: "user_id", type: "number", required: true, description: "用户 ID" }],
    rawBody: true,
    description: "更新用户返利设置 (使用 --json 传入)",
  },
  {
    domain: "affiliates",
    action: "clear-user",
    method: "DELETE",
    path: "/admin/affiliates/users/:user_id",
    pathParams: [{ name: "user_id", type: "number", required: true, description: "用户 ID" }],
    description: "清除用户返利设置",
  },
];
