import type { EndpointDef } from "../types.js";

export const settingsEndpoints: EndpointDef[] = [
  {
    domain: "settings",
    action: "get",
    method: "GET",
    path: "/admin/settings",
    description: "获取全部系统设置",
  },
  {
    domain: "settings",
    action: "update",
    method: "PUT",
    path: "/admin/settings",
    rawBody: true,
    description: "更新系统设置 (使用 --json 传入)",
  },
  {
    domain: "settings",
    action: "test-smtp",
    method: "POST",
    path: "/admin/settings/test-smtp",
    description: "测试 SMTP 连接",
  },
  {
    domain: "settings",
    action: "send-test-email",
    method: "POST",
    path: "/admin/settings/send-test-email",
    rawBody: true,
    description: "发送测试邮件",
  },
  {
    domain: "settings",
    action: "email-templates",
    method: "GET",
    path: "/admin/settings/email-templates",
    description: "列出邮件模板",
  },
  {
    domain: "settings",
    action: "email-template-preview",
    method: "POST",
    path: "/admin/settings/email-template-preview",
    rawBody: true,
    description: "预览邮件模板",
  },
  {
    domain: "settings",
    action: "get-email-template",
    method: "GET",
    path: "/admin/settings/email-templates/:event/:locale",
    pathParams: [
      { name: "event", type: "string", required: true, description: "事件名" },
      { name: "locale", type: "string", required: true, description: "语言" },
    ],
    description: "获取邮件模板",
  },
  {
    domain: "settings",
    action: "update-email-template",
    method: "PUT",
    path: "/admin/settings/email-templates/:event/:locale",
    pathParams: [
      { name: "event", type: "string", required: true, description: "事件名" },
      { name: "locale", type: "string", required: true, description: "语言" },
    ],
    rawBody: true,
    description: "更新邮件模板",
  },
  {
    domain: "settings",
    action: "restore-email-template",
    method: "POST",
    path: "/admin/settings/email-templates/:event/:locale/restore-official",
    pathParams: [
      { name: "event", type: "string", required: true, description: "事件名" },
      { name: "locale", type: "string", required: true, description: "语言" },
    ],
    description: "恢复官方邮件模板",
  },
  // Admin API Key
  {
    domain: "settings",
    action: "admin-key-get",
    method: "GET",
    path: "/admin/settings/admin-api-key",
    description: "获取 Admin API Key 状态",
    aliases: ["admin-key"],
  },
  {
    domain: "settings",
    action: "admin-key-regenerate",
    method: "POST",
    path: "/admin/settings/admin-api-key/regenerate",
    description: "重新生成 Admin API Key",
  },
  {
    domain: "settings",
    action: "admin-key-delete",
    method: "DELETE",
    path: "/admin/settings/admin-api-key",
    description: "删除 Admin API Key",
  },
  // 子设置项
  {
    domain: "settings",
    action: "overload-cooldown",
    method: "GET",
    path: "/admin/settings/overload-cooldown",
    description: "获取过载冷却设置",
  },
  {
    domain: "settings",
    action: "update-overload-cooldown",
    method: "PUT",
    path: "/admin/settings/overload-cooldown",
    rawBody: true,
    description: "更新过载冷却设置",
  },
  {
    domain: "settings",
    action: "rate-limit-429-cooldown",
    method: "GET",
    path: "/admin/settings/rate-limit-429-cooldown",
    description: "获取 429 限流冷却设置",
  },
  {
    domain: "settings",
    action: "update-rate-limit-429-cooldown",
    method: "PUT",
    path: "/admin/settings/rate-limit-429-cooldown",
    rawBody: true,
    description: "更新 429 限流冷却设置",
  },
  {
    domain: "settings",
    action: "stream-timeout",
    method: "GET",
    path: "/admin/settings/stream-timeout",
    description: "获取流超时设置",
  },
  {
    domain: "settings",
    action: "update-stream-timeout",
    method: "PUT",
    path: "/admin/settings/stream-timeout",
    rawBody: true,
    description: "更新流超时设置",
  },
  {
    domain: "settings",
    action: "rectifier",
    method: "GET",
    path: "/admin/settings/rectifier",
    description: "获取纠正器设置",
  },
  {
    domain: "settings",
    action: "update-rectifier",
    method: "PUT",
    path: "/admin/settings/rectifier",
    rawBody: true,
    description: "更新纠正器设置",
  },
  {
    domain: "settings",
    action: "beta-policy",
    method: "GET",
    path: "/admin/settings/beta-policy",
    description: "获取 Beta 策略设置",
  },
  {
    domain: "settings",
    action: "update-beta-policy",
    method: "PUT",
    path: "/admin/settings/beta-policy",
    rawBody: true,
    description: "更新 Beta 策略设置",
  },
  {
    domain: "settings",
    action: "web-search-emulation",
    method: "GET",
    path: "/admin/settings/web-search-emulation",
    description: "获取 Web Search 模拟配置",
  },
  {
    domain: "settings",
    action: "update-web-search-emulation",
    method: "PUT",
    path: "/admin/settings/web-search-emulation",
    rawBody: true,
    description: "更新 Web Search 模拟配置",
  },
  {
    domain: "settings",
    action: "test-web-search-emulation",
    method: "POST",
    path: "/admin/settings/web-search-emulation/test",
    description: "测试 Web Search 模拟",
  },
  {
    domain: "settings",
    action: "reset-web-search-usage",
    method: "POST",
    path: "/admin/settings/web-search-emulation/reset-usage",
    description: "重置 Web Search 用量",
  },
];
