import type { EndpointDef } from "../types.js";

export const subscriptionEndpoints: EndpointDef[] = [
  {
    domain: "subscriptions",
    action: "list",
    method: "GET",
    path: "/admin/subscriptions",
    queryParams: [
      { name: "page", type: "number", required: false, description: "页码" },
      { name: "page_size", type: "number", required: false, description: "每页数量" },
      { name: "user_id", type: "number", required: false, description: "用户 ID" },
      { name: "group_id", type: "number", required: false, description: "分组 ID" },
      { name: "status", type: "string", required: false, description: "状态筛选" },
      { name: "platform", type: "string", required: false, description: "平台筛选" },
      { name: "sort_by", type: "string", required: false, description: "排序字段" },
      { name: "sort_order", type: "string", required: false, description: "asc/desc" },
    ],
    isPaginated: true,
    description: "列出所有订阅",
    aliases: ["ls"],
  },
  {
    domain: "subscriptions",
    action: "get",
    method: "GET",
    path: "/admin/subscriptions/:id",
    pathParams: [{ name: "id", type: "number", required: true, description: "订阅 ID" }],
    description: "获取订阅详情",
  },
  {
    domain: "subscriptions",
    action: "progress",
    method: "GET",
    path: "/admin/subscriptions/:id/progress",
    pathParams: [{ name: "id", type: "number", required: true, description: "订阅 ID" }],
    description: "获取订阅进度",
  },
  {
    domain: "subscriptions",
    action: "assign",
    method: "POST",
    path: "/admin/subscriptions/assign",
    bodyParams: [
      { name: "user_id", type: "number", required: true, description: "用户 ID" },
      { name: "group_id", type: "number", required: true, description: "分组 ID" },
      { name: "validity_days", type: "number", required: false, description: "有效天数" },
      { name: "notes", type: "string", required: false, description: "备注" },
    ],
    description: "分配订阅",
  },
  {
    domain: "subscriptions",
    action: "bulk-assign",
    method: "POST",
    path: "/admin/subscriptions/bulk-assign",
    bodyParams: [
      { name: "user_ids", type: "json", required: true, description: "用户 ID 列表 (JSON 数组)" },
      { name: "group_id", type: "number", required: true, description: "分组 ID" },
      { name: "validity_days", type: "number", required: false, description: "有效天数" },
      { name: "notes", type: "string", required: false, description: "备注" },
    ],
    description: "批量分配订阅",
  },
  {
    domain: "subscriptions",
    action: "extend",
    method: "POST",
    path: "/admin/subscriptions/:id/extend",
    pathParams: [{ name: "id", type: "number", required: true, description: "订阅 ID" }],
    bodyParams: [
      { name: "days", type: "number", required: true, description: "延长天数" },
    ],
    description: "延长订阅",
  },
  {
    domain: "subscriptions",
    action: "reset-quota",
    method: "POST",
    path: "/admin/subscriptions/:id/reset-quota",
    pathParams: [{ name: "id", type: "number", required: true, description: "订阅 ID" }],
    description: "重置订阅配额",
  },
  {
    domain: "subscriptions",
    action: "revoke",
    method: "DELETE",
    path: "/admin/subscriptions/:id",
    pathParams: [{ name: "id", type: "number", required: true, description: "订阅 ID" }],
    description: "撤销订阅",
  },
];
