import type { EndpointDef } from "../types.js";

export const userEndpoints: EndpointDef[] = [
  {
    domain: "users",
    action: "list",
    method: "GET",
    path: "/admin/users",
    queryParams: [
      { name: "page", type: "number", required: false, description: "页码" },
      { name: "page_size", type: "number", required: false, description: "每页数量" },
      { name: "status", type: "string", required: false, description: "状态筛选" },
      { name: "role", type: "string", required: false, description: "角色筛选" },
      { name: "search", type: "string", required: false, description: "搜索关键词" },
      { name: "group_name", type: "string", required: false, description: "分组名筛选" },
      { name: "api_key_group_id", type: "number", required: false, description: "API Key 分组 ID" },
      { name: "sort_by", type: "string", required: false, description: "排序字段" },
      { name: "sort_order", type: "string", required: false, description: "asc/desc" },
      { name: "include_subscriptions", type: "boolean", required: false, description: "包含订阅信息" },
    ],
    isPaginated: true,
    description: "列出所有用户",
    aliases: ["ls"],
  },
  {
    domain: "users",
    action: "get",
    method: "GET",
    path: "/admin/users/:id",
    pathParams: [{ name: "id", type: "number", required: true, description: "用户 ID" }],
    queryParams: [
      { name: "include_deleted", type: "boolean", required: false, description: "包含已删除用户" },
    ],
    description: "获取用户详情",
  },
  {
    domain: "users",
    action: "create",
    method: "POST",
    path: "/admin/users",
    bodyParams: [
      { name: "email", type: "string", required: true, description: "邮箱" },
      { name: "password", type: "string", required: true, description: "密码" },
      { name: "username", type: "string", required: false, description: "用户名" },
      { name: "notes", type: "string", required: false, description: "备注" },
      { name: "balance", type: "number", required: false, description: "初始余额" },
      { name: "concurrency", type: "number", required: false, description: "并发限制" },
      { name: "rpm_limit", type: "number", required: false, description: "RPM 限制" },
      { name: "allowed_groups", type: "json", required: false, description: "允许的分组 IDs (JSON 数组)" },
    ],
    description: "创建用户",
  },
  {
    domain: "users",
    action: "update",
    method: "PUT",
    path: "/admin/users/:id",
    pathParams: [{ name: "id", type: "number", required: true, description: "用户 ID" }],
    bodyParams: [
      { name: "email", type: "string", required: false, description: "邮箱" },
      { name: "password", type: "string", required: false, description: "密码" },
      { name: "username", type: "string", required: false, description: "用户名" },
      { name: "notes", type: "string", required: false, description: "备注" },
      { name: "balance", type: "number", required: false, description: "余额" },
      { name: "concurrency", type: "number", required: false, description: "并发限制" },
      { name: "rpm_limit", type: "number", required: false, description: "RPM 限制" },
      { name: "status", type: "string", required: false, description: "状态" },
      { name: "allowed_groups", type: "json", required: false, description: "允许的分组 IDs (JSON 数组)" },
      { name: "group_rates", type: "json", required: false, description: "分组费率 (JSON)" },
    ],
    description: "更新用户",
  },
  {
    domain: "users",
    action: "delete",
    method: "DELETE",
    path: "/admin/users/:id",
    pathParams: [{ name: "id", type: "number", required: true, description: "用户 ID" }],
    description: "删除用户",
  },
  {
    domain: "users",
    action: "update-balance",
    method: "POST",
    path: "/admin/users/:id/balance",
    pathParams: [{ name: "id", type: "number", required: true, description: "用户 ID" }],
    bodyParams: [
      { name: "balance", type: "number", required: true, description: "金额" },
      { name: "operation", type: "string", required: true, description: "操作: set/add/subtract" },
      { name: "notes", type: "string", required: false, description: "备注" },
    ],
    description: "更新用户余额",
  },
  {
    domain: "users",
    action: "api-keys",
    method: "GET",
    path: "/admin/users/:id/api-keys",
    pathParams: [{ name: "id", type: "number", required: true, description: "用户 ID" }],
    queryParams: [
      { name: "page", type: "number", required: false, description: "页码" },
      { name: "page_size", type: "number", required: false, description: "每页数量" },
      { name: "sort_by", type: "string", required: false, description: "排序字段" },
      { name: "sort_order", type: "string", required: false, description: "asc/desc" },
    ],
    isPaginated: true,
    description: "获取用户的 API Keys",
  },
  {
    domain: "users",
    action: "usage",
    method: "GET",
    path: "/admin/users/:id/usage",
    pathParams: [{ name: "id", type: "number", required: true, description: "用户 ID" }],
    queryParams: [
      { name: "period", type: "string", required: false, description: "统计周期 (默认 month)" },
    ],
    description: "获取用户用量",
  },
  {
    domain: "users",
    action: "balance-history",
    method: "GET",
    path: "/admin/users/:id/balance-history",
    pathParams: [{ name: "id", type: "number", required: true, description: "用户 ID" }],
    queryParams: [
      { name: "page", type: "number", required: false, description: "页码" },
      { name: "page_size", type: "number", required: false, description: "每页数量" },
      { name: "type", type: "string", required: false, description: "记录类型" },
    ],
    isPaginated: true,
    description: "获取用户余额历史",
  },
  {
    domain: "users",
    action: "replace-group",
    method: "POST",
    path: "/admin/users/:id/replace-group",
    pathParams: [{ name: "id", type: "number", required: true, description: "用户 ID" }],
    bodyParams: [
      { name: "old_group_id", type: "number", required: true, description: "旧分组 ID" },
      { name: "new_group_id", type: "number", required: true, description: "新分组 ID" },
    ],
    description: "替换用户分组",
  },
  {
    domain: "users",
    action: "rpm-status",
    method: "GET",
    path: "/admin/users/:id/rpm-status",
    pathParams: [{ name: "id", type: "number", required: true, description: "用户 ID" }],
    description: "获取用户 RPM 状态",
  },
  {
    domain: "users",
    action: "batch-concurrency",
    method: "POST",
    path: "/admin/users/batch-concurrency",
    rawBody: true,
    description: "批量更新用户并发",
  },
  {
    domain: "users",
    action: "platform-quotas",
    method: "GET",
    path: "/admin/users/:id/platform-quotas",
    pathParams: [{ name: "id", type: "number", required: true, description: "用户 ID" }],
    description: "获取用户平台配额",
  },
  {
    domain: "users",
    action: "update-platform-quotas",
    method: "PUT",
    path: "/admin/users/:id/platform-quotas",
    pathParams: [{ name: "id", type: "number", required: true, description: "用户 ID" }],
    rawBody: true,
    description: "更新用户平台配额",
  },
  {
    domain: "users",
    action: "reset-platform-quota",
    method: "POST",
    path: "/admin/users/:id/platform-quotas/reset",
    pathParams: [{ name: "id", type: "number", required: true, description: "用户 ID" }],
    description: "重置用户平台配额窗口",
  },
  {
    domain: "users",
    action: "attributes",
    method: "GET",
    path: "/admin/users/:id/attributes",
    pathParams: [{ name: "id", type: "number", required: true, description: "用户 ID" }],
    description: "获取用户自定义属性",
  },
  {
    domain: "users",
    action: "update-attributes",
    method: "PUT",
    path: "/admin/users/:id/attributes",
    pathParams: [{ name: "id", type: "number", required: true, description: "用户 ID" }],
    rawBody: true,
    description: "更新用户自定义属性",
  },
  {
    domain: "users",
    action: "bind-auth-identity",
    method: "POST",
    path: "/admin/users/:id/auth-identities",
    pathParams: [{ name: "id", type: "number", required: true, description: "用户 ID" }],
    bodyParams: [
      { name: "provider_type", type: "string", required: true, description: "认证提供方类型" },
      { name: "provider_key", type: "string", required: true, description: "认证提供方 Key" },
      { name: "provider_subject", type: "string", required: true, description: "认证 Subject" },
      { name: "issuer", type: "string", required: false, description: "签发方" },
      { name: "metadata", type: "json", required: false, description: "元数据 (JSON)" },
      { name: "channel", type: "string", required: false, description: "渠道" },
    ],
    description: "绑定用户认证身份",
  },
  {
    domain: "users",
    action: "subscriptions",
    method: "GET",
    path: "/admin/users/:id/subscriptions",
    pathParams: [{ name: "id", type: "number", required: true, description: "用户 ID" }],
    queryParams: [
      { name: "page", type: "number", required: false, description: "页码" },
      { name: "page_size", type: "number", required: false, description: "每页数量" },
    ],
    isPaginated: true,
    description: "获取用户订阅列表",
  },
];
